### ISSUE TITLE
This project reported an error

### ISSUE THREAD

**Issue by molyswu** [soCzech/GenHowTo#2]
Try to:
python genhowto.py --weights_path ./weights/GenHowTo_controlnet.pth --input_image  ./imgs/input/01.png     --prompt  "a person slicing an avacado on a cutting board"  --output_path ./imgs/output/output.png  --num_images 1

\GenHowTo-main\genhowto_utils.py", line 16, in load_genhowto_model
    with open(os.path.join(weights_path, "GenHowTo_controlnet_config.json")) as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './weights/GenHowTo_controlnet.pth\\GenHowTo_controlnet_config.json'
   
Thanks!
 molyswu

**Comment by soCzech** [comment]
`--weights_path` must be the weights directory, not a file.

**Comment by molyswu** [comment]
Tried to :weights/GenHowTo-STATES-96h-v1?  or (https://data.ciirc.cvut.cz/public/projects/2023GenHowTo/weights/GenHowTo-STATES-96h-v1/GenHowTo_controlnet.pth)    , a same  issue.
