### ISSUE TITLE
Doubt Regarding Qualitative Results .

### ISSUE THREAD

**Issue by Surya-Abhinai** [soCzech/GenHowTo#6]
I am encountering some difficulties in achieving the same level of foreground and background consistency as presented in your work. My results so far have been quite inconsistent and not up to the mark.

Could you please provide any insights  on how to achieve similar results? Are there specific techniques, preprocessing steps which you used , that you recommend to improve the consistency of the images?

**Comment by soCzech** [comment]
Please share the input and output images and text prompts.

**Comment by Surya-Abhinai** [comment]
![image](https://github.com/user-attachments/assets/f610d8d7-d393-43c1-8752-763f97ad4056)

**Comment by Surya-Abhinai** [comment]
![image](https://github.com/user-attachments/assets/e3116159-0b5b-4a72-b52a-fab643dd0428)

Prompt :- A man holding the football .

**Comment by soCzech** [comment]
Yeah, these are quite out of distribution images and prompts... Most of the training data is indoors, with a heavy focus on cooking. You may need to play with the noise, i.e., potentially increasing `--num_steps_to_skip`. But I am not sure how well this is going to work;/
